name: Build, Test, and Start Sonarqube

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Compile the project
        run: ./gradlew build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4 
        with:
          name: sonar-distribution
          path: sonar-application/build/distributions/sonar-application-*.zip


  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Download build artifact
        uses: actions/download-artifact@v4 
        with:
          name: sonar-distribution

      - name: Unzip distribution
        run: unzip sonar-application-*.zip && mv sonarqube-* ./sonar-application/build/distributions/

      - name: Run tests 
        run: ./gradlew test

      - name: Output test results
        run: grep -B 1 -A 1 successful sonar-scanner-engine/build/reports/tests/test/index.html


  start-sonarqube:
    needs: 
      - build
      - test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download build artifact
        uses: actions/download-artifact@v4 
        with:
          name: sonar-distribution

      - name: Unzip distribution
        run: unzip sonar-application-*.zip

      - name: Start the server
        run: sonarqube-*/bin/linux-x86-64/sonar.sh start
